packages:
  - "apps/*"
  - "workers/*"
  - "packages/*"
allowBuilds:
  '@biomejs/biome': false
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': false
  bcrypt: false
  esbuild: false
  msgpackr-extract: false
  prisma: false
  protobufjs: false
  sharp: false
